export const BoardActions = {
	SQUARE_CONFIG_UPDATE: 'SQUARE_CONFIG_UPDATE',
	ADD_ACTIVE_SQUARE: 'ADD_ACTIVE_SQUARE',
	DELETE_ACTIVE_SQUARE: 'DELETE_ACTIVE_SQUARE',
	PICKED_MODE_UPDATE: 'PICKED_MODE_UPDATE'
} as const;