name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Push to existing publish branch
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout publish
        git rm -r .  # Remove existing files in publish branch
        git commit -m "Remove existing files in publish branch"
        git push origin publish
        git checkout main
        git checkout publish -- dist  # Copy 'dist' folder from main to publish branch
        git add .
        git commit -m "Auto-publish from main branch"
        git push origin publish